name: Build and Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker-compose -f docker-compose.yml build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Ping Server
        run: ping -c 4 ${{ secrets.SERVER_IP }}

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/dave/projects/bot_ci_cd_00
            docker-compose -f docker-compose.yml down --remove-orphans
            git pull
            docker-compose -f docker-compose.yml build
            docker-compose -f docker-compose.yml up -d
